Create database MyDatabase;
use mydatabase;

--- Create  Employees Table

create table Employees 
(
   EMPNO	INT NOT NULL,
   ENAME  VARCHAR(10),
   JOB	VARCHAR(10),
   MGR	INT,
   HIREDATE DATE,
   SAL INT,
   COMM INT,
   DEPTNO INT NOT NULL,
   CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPNO)
);


-- INCERT DATA INTO TABLE 

INSERT INTO EMPLOYEES VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-1981',5000,NULL,10),
		         (7698,'BLAKE','MANAGER',7839,'1-MAY-1981',2850,NULL,30);

INSERT INTO EMPLOYEES VALUES  (7782,'CLARK','MANAGER',7839,'9-JUN-1981',2450,NULL,10),
		          (7566,'JONES','MANAGER',7839,'2-APR-1981',2975,NULL,20),
			(7654,'MARTIN','SALESMAN',7698,'28-SEP-1981',1250,1400,30),
			(7499,'ALLEN','SALESMAN',7698,'20-FEB-1981',1600,300,30),
			(7844,'TURNER','SALESMAN',7698,'8-SEP-1981',1500,0,30),
			(7900,'JAMES','CLERK',7698,'3-DEC-1981',950,NULL,30),
			(7521,'WARD','SALESMAN',7698,'22-FEB-1981',1250,500,30),
			(7902,'FORD','ANALYST',7566,'3-DEC-1981',3000,NULL,20);

SELECT * FROM Employees;

SELECT DISTINCT SAL FROM Employees
INTERSECT 
SELECT SAL, ENAME FROM Employees WHERE SAL IN ( SELECT DISTINCT SAL FROM Employees WHERE SAL < 1500);


SELECT DISTINCT JOB, DEPTNO FROM EMPLOYEES;

--- WHERE CLAUSE AND ORDER BY ASC / DESC 

SELECT ENAME, JOB, DEPTNO, SAL
FROM EMPLOYEES
WHERE DEPTNO=30
ORDER BY SAL DESC;

--- SELECT TOP CLAUSE 

SELECT TOP (3) ENAME, SAL, DEPTNO   FROM Employees;


--- AND OR NOT LOGICAL OPARETOR 

SELECT TOP 3 SAL FROM EMPLOYEES 
WHERE NOT JOB = 'ANALYST'
ORDER BY SAL DESC;

SELECT ENAME FROM EMPLOYEES 
WHERE  JOB NOT IN  ('MANAGER','SALESMAN') AND DEPTNO = 30;

SELECT * FROM Employees;

SELECT * FROM Employees
WHERE COMM IS NOT NULL;

SELECT * FROM Employees
WHERE COMM IS NULL;

SELECT ENAME FROM Employees 
WHERE ENAME LIKE '%S';

SELECT ENAME FROM Employees 
WHERE ENAME LIKE '%S%';

SELECT ENAME FROM Employees 
WHERE ENAME LIKE '_L%';

SELECT ENAME FROM Employees 
WHERE ENAME LIKE '%E_';

SELECT ENAME, JOB, SAL from
EMPLOYEES 
WHERE SAL BETWEEN 1000 AND 2000;

SELECT ENAME, HIREDATE from
EMPLOYEES 
WHERE MGR IS NOT NULL;

SELECT ENAME FROM EMPLOYEES 
WHERE ENAME LIKE 'J%ES';

SELECT ENAME, DEPTNO 
FROM EMPLOYEES
WHERE ENAME LIKE '_L%' AND LEN (ENAME) = 5;

SELECT ENAME, SAL FROM 
EMPLOYEES 
WHERE SAL >= 2500;

SELECT SAL AS OLD_SAL, ROUND( SAL+(SAL*.06) ,0) AS NEW_SAL
FROM EMPLOYEES;

--- CASE STATEMENT 

SELECT ENAME, SAL,
CASE 
WHEN SAL BETWEEN 2000 AND 1000 THEN 'AVERAGE'
WHEN SAL >= 2000 THEN 'HIGH'
ELSE 'LOW'
END AS SALRANK
FROM 
EMPLOYEES;











