--- ALTER TABLE CHALLENGES : 

SELECT * FROM HCM.employees;
GO 

ALTER TABLE HCM.EMPLOYEES
DROP COLUMN TERMINATION_DATE;

ALTER TABLE HCM.EMPLOYEES
ADD TERMINATION_DATE DATETIME;

ALTER TABLE OES.CUSTOMERS
ALTER COLUMN FIRST_NAME NVARCHAR(50);

ALTER TABLE OES.CUSTOMERS
ALTER COLUMN LAST_NAME NVARCHAR(50);
	   
SELECT * FROM OES.CUSTOMERS;

EXECUTE SP_RENAME 'OES.CUSTOMERS.NEW_PHONE1','MAIN_PHONE','COLUMN';

SELECT * FROM HCM.departments;

ALTER TABLE HCM.DEPARTMENTS
ADD CONSTRAINT UN_DEPARTMENT_DEP_NAME UNIQUE ( DEPARTMENT_NAME);

SELECT 
	TABLE_SCHEMA,
	TABLE_NAME,
	COLUMN_NAME,
	DATA_TYPE

FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HCM'
ORDER BY TABLE_NAME;


ALTER TABLE HCM.JOBS
ADD CONSTRAINT CHECK_JOBS_MIN_SALARY CHECK (MIN_SALARY > 0);

INSERT INTO HCM.jobs ( job_title, min_salary)
VALUES('MD',3400);

DELETE  HCM.JOBS
WHERE job_title = 'MD' AND min_salary = 3400;

ALTER TABLE HCM.EMPLOYEES 
ADD CONSTRAINT CK_EMPLOYEES_SALARY CHECK (SALARY > 0);

SELECT * FROM HCM.EMPLOYEES;

UPDATE  HCM.EMPLOYEES
SET salary =1 WHERE employee_id = 206;

SELECT * FROM HCM.EMPLOYEES
WHERE employee_id = 206;

DELETE HCM.employees
WHERE employee_id = 206;



