use MyDatabase;
go

--concatenation 

select ename + ' ' + job as Ename_job from Employees;

--- substring 

select SUBSTRING(JOB,1,3) AS JOB_TITLE, JOB FROM Employees;

SELECT LEN(JOB) AS LENGTH_J, JOB FROM Employees;

SELECT * FROM Employees;

SELECT COMM, ISNULL(COMM,0) FROM Employees;


SELECT * FROM Employees;

SELECT * , REPLACE(JOB,'SALESMAN','SALLER') AS NEW_JOB 
FROM Employees;

SELECT  lower(ENAME) AS LOW_NAME,SUBSTRING(JOB,1,4) AS JOB_TITLE, LEN(ENAME) AS NAME_LEN FROM EMPLOYEES;

select * from Employees;

SELECT  JOB, CONVERT(varchar, AVG(SAL) OVER(PARTITION BY JOB  )) AS PARTITION_BY
FROM Employees
ORDER BY PARTITION_BY;

SELECT HIREDATE, CONVERT(datetime,HIREDATE) AS NEW_HIREDATE FROM Employees;


---DATEDIFF

SELECT ENAME, DAY(HIREDATE), YEAR(HIREDATE) FROM EMPLOYEES
WHERE MONTH(HIREDATE) = 12;


SELECT LOG(5);
SELECT POWER(2,3);
SELECT ABS(-123.3);

SELECT CEILING(123213.23);


--- AGGREGATE FUNCTION 

SELECT COUNT(ENAME) FROM Employees;
SELECT DISTINCT(JOB) FROM Employees;

SELECT STDEV(SAL) FROM Employees;

SELECT COUNT(*), MIN(SAL), MAX(SAL) FROM EMPLOYEES WHERE JOB = 'SALESMAN';

SELECT SUM(SAL), AVG(SAL), STDEV(SAL)
FROM EMPLOYEES WHERE JOB ='MANAGER';

SELECT JOB, COUNT(JOB) COUNT_JOB FROM Employees
GROUP BY JOB
HAVING JOB LIKE 'AN%';



SELECT  DEPTNO,JOB, COUNT(EMPNO)
FROM EMPLOYEES 
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO;

SELECT JOB, AVG(SAL) 
FROM EMPLOYEES 
GROUP BY JOB
HAVING AVG(SAL) BETWEEN 2000 AND 4000;



CREATE TABLE LOCATION 
(
	LOCATION_ID INT PRIMARY KEY NOT NULL,
	REGIONAL_GROUP VARCHAR (50) 
);
 
INSERT INTO LOCATION VALUES (122,'NEW YORK');
INSERT INTO LOCATION VALUES (123,'DALLAS');
INSERT INTO LOCATION VALUES (124,'CHICAGO');
INSERT INTO LOCATION VALUES (167,'BOSTON');
 
CREATE TABLE JOB
(
	JOB_ID INT PRIMARY KEY NOT NULL,
	JOB_NAME VARCHAR (50) 
);
 
INSERT INTO JOB VALUES (667,'CLERK');
INSERT INTO JOB VALUES (669,'ANALYST');
INSERT INTO JOB VALUES (670,' SALESPERSON');
INSERT INTO JOB VALUES (671,'MANAGER');
 
CREATE TABLE DEPARTMENT 
(
	DEPARTMENT_ID INT PRIMARY KEY NOT NULL,
	NAME VARCHAR (20),
	LOCATION_ID INT NOT NULL,
	FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);
 
INSERT INTO DEPARTMENT VALUES (10,'ACCOUNTING',122);
INSERT INTO DEPARTMENT VALUES (20,'RESEARCH',124);
INSERT INTO DEPARTMENT VALUES (30,'SALES',123);
INSERT INTO DEPARTMENT VALUES (40,'OPERATIONS',167);
 
CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT PRIMARY KEY NOT NULL,
LAST_NAME VARCHAR (20),
FIRST_NAME VARCHAR (20),
MIDDLE_NAME VARCHAR (20),
JOB_ID INT NOT NULL,
FOREIGN KEY (JOB_ID) REFERENCES JOB(JOB_ID),
MANAGER_ID INT,
HIREDATE VARCHAR (15),
SALARY INT,
COMM INT,
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);


---SQL JOIN 
