
--- SCALAR FUNCTIONS ----

------------ STRING MANIPULETION ---------------------------
-- charindex( substring, string, Starting_position-optional)
-- left(string, number_of_chr)
-- SUBSTRING( STRING, START_POSITION, LENGTH) 

------------- DATE AND TIME MANIPULETION -----------------------
--- GETDATE() , THIS FUNCTION RETURNS THE CURRENT DATE.
SELECT GETDATE(); -- OUTPUT = 2025-02-23 00:08:18.063

--- CAST() FUNCTION MANIPULATE THE GETDATE FUNCTION 
SELECT CAST(GETDATE() AS DATE) AS ONLY_DATE; --- OUTPUT = 2025-02-23

--- DATEPART() FUNCTION CAN RETURN A PART OF A DATE
--- DATEPART(YEAR, HIRE_DATE) AND THE OUTPUT IS 1994

--- DATENAME() FUNCTION ALSO USE FULL 
--- DATENAME( MONTH, HIRE_DATE) AND THE OUTPUT IS JANUARY

--- DATEADD() FUNCTION IS USE FULL, IF WE WANT TO ADD SOME YEARS OR MONTHS OR HOURS OR MINUETS WITH OUR DATA
--- DATEADD(YEAR, 5, HIRE_DATE) THE OUT PUT IS 1999 IF THE REAL HIRE DATE IS 1994

--- DATEDIFF() FUNCTION IS USEFULL WHEN WE WANT TO MESURE THE DATE DIFFERNTS 
--- DATEDIFF( DAY, HIRE_DATE, GATEDATE) HERER GATEDATE()- CURRENT DATE 


