USE SUBQUERY;

CREATE TABLE STUDENTS

(	S_ID INT IDENTITY,
	FNAME VARCHAR(20),
	LNAME VARCHAR(20),
	GENDER CHAR
);

IF ( OBJECT_ID('INCERTSTUDENT')) IS NOT NULL
	DROP TABLE INCERTSTUDENT
GO

SELECT * FROM STUDENTS;

DECLARE @NUMBER INT;
SET @NUMBER = 12;

IF @NUMBER = 12
PRINT 'THE NUMBER IS 12';

--- WE CAN WRITE LIKE THIS 

DECLARE @NUMBER1 INT;
SET @NUMBER1 = 12;

IF @NUMBER1 = 12
	BEGIN 
		PRINT 'THE NUMBER1 IS 12'
	END;


---- IF ELSE STATEMENT WIHT EXISTS FUNCTION

SELECT * FROM HCM.EMPLOYEES; 

IF EXISTS ( SELECT * FROM HCM.EMPLOYEES WHERE FIRST_NAME LIKE 'DonS')
	print ( 'Don is exists in the Employees table')
else 
	print( 'Done is not exists in the Employees table')
;

DECLARE @ROWCOUNT INT ;
DECLARE @ROWCOUNT_DEPARTMENT_60 INT;
SET @ROWCOUNT = ( SELECT COUNT(*) FROM HCM.DEPARTMENTS);
SET @ROWCOUNT_DEPARTMENT_60 = ( SELECT COUNT(*) FROM HCM.DEPARTMENTS WHERE DEPARTMENT_ID = 60);

PRINT( 'ROWCOUNT_DEPARTMENT_60 IS = ' + CAST( @ROWCOUNT_DEPARTMENT_60 AS CHAR)); 
PRINT( 'ROWCOUNT IS = ' + CAST( @ROWCOUNT AS CHAR)); 
PRINT ( CONCAT ( 'TOTAL ROW COUNT = ',CAST(@ROWCOUNT AS CHAR)));
